//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjC349WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advanceoy15_clearmixarea
    {
        public int id { get; set; }
        public string area { get; set; }
        public string position { get; set; }
        public string coil_code { get; set; }
        public string red_tag_coil_layer { get; set; }
        public string label { get; set; }
        public string weight { get; set; }
        public string src_warehouse { get; set; }
        public string dst_warehouse { get; set; }
        public string dst_section { get; set; }
        public string comment { get; set; }
    }
}
