//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjC349WebMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class c349dbEntities_AdvanceOY15_ClearMixArea : DbContext
    {
        public c349dbEntities_AdvanceOY15_ClearMixArea()
            : base("name=c349dbEntities_AdvanceOY15_ClearMixArea")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<advanceoy15_clearmixarea> advanceoy15_clearmixarea { get; set; }
    }
}
