//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjC349WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMakingCargoPlan
    {
        [DisplayName("紀錄編號")]
        public int id { get; set; }
        [DisplayName("庫別")]
        public string warehouse { get; set; }
        [DisplayName("鋼捲標籤")]
        public string label { get; set; }
        [DisplayName("儲區排")]
        public string area { get; set; }
        [DisplayName("儲位")]
        public string pos { get; set; }
        [DisplayName("訂單號碼")]
        public string order_num { get; set; }
        [DisplayName("提單")]
        public string bill_of_ladding { get; set; }
        [DisplayName("船號")]
        public string ship_num { get; set; }
        [DisplayName("艙序")]
        public string making_cargo_plan { get; set; }

        [DisplayName("更新日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
